const icons={w:{k:'♔',q:'♕',r:'♖',b:'♗',n:'♘',p:'♙'},b:{k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'}};
const value={p:1,n:3,b:3,r:5,q:9,k:0}; const files='abcdefgh';
let state,selected=null,legal=[],flipped=false,timer,elapsed={w:0,b:0};
let roomId=null, playerColor=null, gameReady=false;
const socket=typeof io==='function'?io():null;
let audioContext=null, musicTimer=null, musicOn=false, musicStep=0;
const boardEl=document.querySelector('#board'), toast=document.querySelector('#toast');
function initialBoard(){let b=Array.from({length:8},()=>Array(8).fill(null));let back=['r','n','b','q','k','b','n','r'];back.forEach((p,c)=>{b[0][c]={c:'b',p};b[1][c]={c:'b',p:'p'};b[6][c]={c:'w',p:'p'};b[7][c]={c:'w',p}});return b}
function reset(){state={b:initialBoard(),turn:'w',castling:{w:{k:true,q:true},b:{k:true,q:true}},ep:null,history:[],moves:[],ended:false,last:null};selected=null;legal=[];elapsed={w:0,b:0};render();startClock();showToast('New game started — White to move');}
function cloneState(s){return {b:s.b.map(r=>r.map(x=>x?{...x}:null)),turn:s.turn,castling:JSON.parse(JSON.stringify(s.castling)),ep:s.ep?[...s.ep]:null,history:[...s.history],moves:[...s.moves],ended:s.ended,last:s.last?[...s.last]:null}}
function inBoard(r,c){return r>=0&&r<8&&c>=0&&c<8} function enemy(x,color){return x&&x.c!==color}
function pseudoMoves(s,r,c,attacks=false){const piece=s.b[r][c];if(!piece)return[];let out=[],add=(R,C,extra={})=>{if(inBoard(R,C)&&(!s.b[R][C]||enemy(s.b[R][C],piece.c)))out.push({r:R,c:C,...extra})};let dirs;
 if(piece.p==='p'){let d=piece.c==='w'?-1:1,start=piece.c==='w'?6:1; if(!attacks&&inBoard(r+d,c)&&!s.b[r+d][c]){add(r+d,c);if(r===start&&!s.b[r+2*d][c])add(r+2*d,c,{double:true})}for(let dc of[-1,1]){let R=r+d,C=c+dc;if(inBoard(R,C)&&(attacks||enemy(s.b[R][C],piece.c))) {if(attacks||s.b[R][C])add(R,C)} if(!attacks&&s.ep&&s.ep[0]===R&&s.ep[1]===C)add(R,C,{enPassant:true})}}
 if(piece.p==='n'){for(let [dr,dc] of [[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])add(r+dr,c+dc)}
 if('brq'.includes(piece.p)){dirs=[];if('bq'.includes(piece.p))dirs.push([-1,-1],[-1,1],[1,-1],[1,1]);if('rq'.includes(piece.p))dirs.push([-1,0],[1,0],[0,-1],[0,1]);for(let [dr,dc] of dirs){let R=r+dr,C=c+dc;while(inBoard(R,C)){if(!s.b[R][C])out.push({r:R,c:C});else{if(enemy(s.b[R][C],piece.c))out.push({r:R,c:C});break}R+=dr;C+=dc}}}
 if(piece.p==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);if(!attacks&&!isCheck(s,piece.c)){let row=piece.c==='w'?7:0;for(let side of ['k','q']){let rookCol=side==='k'?7:0,between=side==='k'?[5,6]:[1,2,3],pass=side==='k'?[5,6]:[3,2];if(s.castling[piece.c][side]&&between.every(x=>!s.b[row][x])&&s.b[row][rookCol]?.p==='r'&&pass.every(x=>!isAttacked(s,row,x,piece.c==='w'?'b':'w')))out.push({r:row,c:side==='k'?6:2,castle:side})}}}
 return out;}
function isAttacked(s,r,c,by){for(let R=0;R<8;R++)for(let C=0;C<8;C++)if(s.b[R][C]?.c===by&&pseudoMoves(s,R,C,true).some(m=>m.r===r&&m.c===c))return true;return false}
function isCheck(s,color){for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(s.b[r][c]?.c===color&&s.b[r][c].p==='k')return isAttacked(s,r,c,color==='w'?'b':'w');return false}
function applyMove(s,from,m,promotion='q'){let x=s.b[from[0]][from[1]], target=s.b[m.r][m.c];s.b[m.r][m.c]=x;s.b[from[0]][from[1]]=null;if(m.enPassant)s.b[from[0]][m.c]=null;if(x.p==='p'&&(m.r===0||m.r===7))x.p=promotion;if(x.p==='k'){s.castling[x.c].k=s.castling[x.c].q=false;if(m.castle){let row=x.c==='w'?7:0;if(m.castle==='k'){s.b[row][5]=s.b[row][7];s.b[row][7]=null}else{s.b[row][3]=s.b[row][0];s.b[row][0]=null}}}if(x.p==='r'){if(from[1]===0)s.castling[x.c].q=false;if(from[1]===7)s.castling[x.c].k=false}if(target?.p==='r'){if(m.c===0)s.castling[target.c].q=false;if(m.c===7)s.castling[target.c].k=false}s.ep=x.p==='p'&&Math.abs(m.r-from[0])===2?[(m.r+from[0])/2,m.c]:null;s.last=[from[0],from[1],m.r,m.c];s.turn=x.c==='w'?'b':'w'}
function legalMoves(s,r,c){let p=s.b[r][c];if(!p||p.c!==s.turn)return[];return pseudoMoves(s,r,c).filter(m=>{let copy=cloneState(s);applyMove(copy,[r,c],m);return !isCheck(copy,p.c)})}
function notation(from,m,piece,captured){let name=piece.p==='p'?'':piece.p.toUpperCase(), cap=captured||m.enPassant;if(piece.p==='p'&&cap)name=files[from[1]];return name+(cap?'x':'')+files[m.c]+(8-m.r)+(m.castle?' O-O'+(m.castle==='q'?'-O':''):'')}
function chooseSquare(r,c){if(state.ended)return;if(roomId&&!gameReady){showToast('Waiting for your opponent to join.');return}if(roomId&&state.turn!==playerColor){showToast('Waiting for your opponent’s move.');return}let p=state.b[r][c];let choice=legal.find(m=>m.r===r&&m.c===c);if(choice&&selected){let from=selected, piece=state.b[from[0]][from[1]], captured=state.b[r][c];if(piece.p==='p'&&(r===0||r===7)){openPromotion(from,choice);return}commit(from,choice,'q',notation(from,choice,piece,!!captured));return}if(p?.c===state.turn){selected=[r,c];legal=legalMoves(state,r,c);render()}else{selected=null;legal=[];render()}}
function openPromotion(from,m){let wrap=document.querySelector('#promotionOptions');wrap.innerHTML='';for(let p of['q','r','b','n']){let btn=document.createElement('button');btn.value=p;btn.textContent=icons[state.turn][p];btn.onclick=()=>{let piece=state.b[from[0]][from[1]],cap=state.b[m.r][m.c];commit(from,m,p,notation(from,m,piece,!!cap)+'='+p.toUpperCase());document.querySelector('#promotionDialog').close()};wrap.append(btn)}document.querySelector('#promotionDialog').showModal()}
function commit(from,m,promo,note,broadcast=true){state.history.push(cloneState(state));applyMove(state,from,m,promo);state.moves.push(note);selected=null;legal=[];let next=allLegal(state,state.turn);if(!next.length){state.ended=true;let check=isCheck(state,state.turn);state.moves[state.moves.length-1]+=check?'#':' ½–½';showToast(check?`${state.turn==='w'?'Black':'White'} wins by checkmate!`:'Draw — stalemate.')}else if(isCheck(state,state.turn)){state.moves[state.moves.length-1]+='+';showToast('Check!')}render();if(broadcast&&roomId)socket.emit('game:move',{color:playerColor,from,move:m,promo,note:state.moves[state.moves.length-1]})}
function allLegal(s,color){let old=s.turn;s.turn=color;let a=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)a.push(...legalMoves(s,r,c));s.turn=old;return a}
function render(){boardEl.innerHTML='';let rows=flipped?[...Array(8).keys()]:[...Array(8).keys()],cols=[...Array(8).keys()];if(flipped){rows.reverse();cols.reverse()}for(let r of rows)for(let c of cols){let sq=document.createElement('button'),p=state.b[r][c],target=legal.find(x=>x.r===r&&x.c===c);sq.className='square '+((r+c)%2?'dark':'')+(selected?.[0]===r&&selected?.[1]===c?' selected':'')+(state.last?.includes(r)&&state.last?.includes(c)?'':'');if(state.last&&((state.last[0]===r&&state.last[1]===c)||(state.last[2]===r&&state.last[3]===c)))sq.classList.add('last');if(target)sq.classList.add(p?'capture':'target');if(p){let sp=document.createElement('span');sp.className='piece '+(p.c==='w'?'white':'black');sp.textContent=icons[p.c][p.p];sq.append(sp)}sq.onclick=()=>chooseSquare(r,c);boardEl.append(sq)}
 let turnName=state.ended?'Game over':state.turn==='w'?'White to move':'Black to move';document.querySelector('#turnText').textContent=turnName;document.querySelector('#whiteCard .clock').classList.toggle('active',state.turn==='w'&&!state.ended);document.querySelector('#blackCard .clock').classList.toggle('active',state.turn==='b'&&!state.ended);renderHistory();renderMaterial();updateClocks()}
function renderHistory(){let el=document.querySelector('#moveList');if(!state.moves.length){el.innerHTML='<li class="empty-history">The board is ready.</li>';return}let html='';for(let i=0;i<state.moves.length;i+=2)html+=`<li><span class="move-no">${i/2+1}.</span><span>${state.moves[i]||''}</span><span>${state.moves[i+1]||''}</span></li>`;el.innerHTML=html;el.scrollTop=el.scrollHeight}
function renderMaterial(){let lost={w:[],b:[]};for(let type of ['q','r','b','n','p']){let totals={w:0,b:0};for(let row of state.b)for(let x of row)if(x?.p===type)totals[x.c]++;for(let color of ['w','b'])for(let i=0;i<(type==='p'?8:type==='n'||type==='b'?2:1)-totals[color];i++)lost[color].push(icons[color][type])}document.querySelector('#whiteCaptured').textContent=lost.b.join('');document.querySelector('#blackCaptured').textContent=lost.w.join('');document.querySelector('#whiteMaterial').textContent=lost.b.join('')||'—';document.querySelector('#blackMaterial').textContent=lost.w.join('')||'—';let score=lost.b.reduce((a,x)=>a+Object.entries(icons.b).find(([,v])=>v===x)?.[0]&&0,0);document.querySelector('#materialScore').textContent='='}
function updateClocks(){for(let c of ['w','b']){let sec=Math.max(0,600-elapsed[c]),t=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;document.querySelector(c==='w'?'#whiteClock':'#blackClock').textContent=t}}
function startClock(){clearInterval(timer);timer=setInterval(()=>{if(!state.ended){elapsed[state.turn]++;updateClocks()}},1000)}function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
function playNote(frequency,when,duration,volume=.025){let osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.value=frequency;gain.gain.setValueAtTime(0.0001,when);gain.gain.exponentialRampToValueAtTime(volume,when+.06);gain.gain.exponentialRampToValueAtTime(.0001,when+duration);osc.connect(gain).connect(audioContext.destination);osc.start(when);osc.stop(when+duration+.04)}
function musicBeat(){if(!musicOn||!audioContext)return;let notes=[220,261.63,329.63,392,329.63,261.63,293.66,349.23];let now=audioContext.currentTime;playNote(notes[musicStep%notes.length],now,.65,.018);if(musicStep%4===0)playNote(notes[(musicStep+2)%notes.length]/2,now,.95,.012);musicStep++;musicTimer=setTimeout(musicBeat,720)}
function toggleMusic(){musicOn=!musicOn;let button=document.querySelector('#soundButton');if(musicOn){audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();musicBeat();button.textContent='♫';showToast('Background music on')}else{clearTimeout(musicTimer);button.textContent='♩';showToast('Background music off')}}
document.querySelector('#newGameButton').onclick=()=>roomId?socket.emit('game:reset'):reset();document.querySelector('#undoButton').onclick=()=>{if(roomId){showToast('Undo is available in local games only.');return}if(!state.history.length)return;state=state.history.pop();selected=null;legal=[];render();showToast('Move undone')};document.querySelector('#flipButton').onclick=()=>{flipped=!flipped;render()};document.querySelector('#soundButton').onclick=toggleMusic;
const roomDialog=document.querySelector('#roomDialog'),roomMessage=document.querySelector('#roomMessage'),roomDisplay=document.querySelector('#roomCodeDisplay');
function updateRoomLabel(text,online=false){document.querySelector('#roomStatus').textContent=text;document.querySelector('.room-status i').style.background=online?'#7ecf92':'#d0a14b'}
function enterRoom(result){roomId=result.roomId;playerColor=result.color;gameReady=!!result.ready;roomDisplay.hidden=false;roomDisplay.querySelector('strong').textContent=roomId;roomMessage.textContent=`You are playing ${playerColor==='w'?'White':'Black'}. Share the code with your friend.`;updateRoomLabel(`ROOM ${roomId}`,true);flipped=playerColor==='b';reset()}
document.querySelector('#roomButton').onclick=()=>roomDialog.showModal();document.querySelector('#createRoomButton').onclick=()=>socket?.emit('room:create',null,result=>{if(result.ok)enterRoom(result)});document.querySelector('#joinRoomButton').onclick=()=>socket?.emit('room:join',document.querySelector('#roomCode').value,result=>{if(result.ok){enterRoom(result);roomDialog.close()}else showToast(result.error)});
if(socket){socket.on('room:update',info=>{gameReady=info.ready;if(info.ready){roomDisplay.querySelector('small').textContent='Opponent connected — game on!';showToast('Opponent connected. Game on!')}});socket.on('game:move',payload=>{if(payload.color!==playerColor)commit(payload.from,payload.move,payload.promo,payload.note,false)});socket.on('game:reset',()=>reset());socket.on('opponent:left',()=>{gameReady=false;showToast('Your opponent left the room.')})}
reset();
